apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.applicationName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.resources.storage }}
