stages:
  - build

build image:
  variables:
    CONTEXT: $CI_PROJECT_DIR
    DOCKERFILE: $CI_PROJECT_DIR/Dockerfile

  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  allow_failure: false
  script:
    - echo $CONTEXT
    - echo $DOCKERFILE
    - ls
    - echo [ -f $DOCKERFILE ] && echo "File exists" || echo "File does not exist"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CONTEXT --dockerfile $DOCKERFILE --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME} --cache=false --compressed-caching=false
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
      when: always